# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{konfigurator}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kriss 'nu7hatch' Kowalik"]
  s.date = %q{2010-10-07}
  s.description = %q{      Konfigurator is a small and flexible configuration toolkit, which allow you 
      to configure your apps, classes or modules with DSL-style or Sinatra-like settings.
}
  s.email = %q{kriss.kowalik@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "konfigurator.gemspec",
     "lib/konfigurator.rb",
     "lib/konfigurator/dsl.rb",
     "lib/konfigurator/simple.rb",
     "test/helper.rb",
     "test/test_dsl.rb",
     "test/test_simple.rb"
  ]
  s.homepage = %q{http://github.com/nu7hatch/konfigurator}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Small and flexible Configuration toolkit inspired i.a. by Sinatra settings.}
  s.test_files = [
    "test/test_dsl.rb",
     "test/test_simple.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<contest>, [">= 0.1.2"])
    else
      s.add_dependency(%q<contest>, [">= 0.1.2"])
    end
  else
    s.add_dependency(%q<contest>, [">= 0.1.2"])
  end
end

